server:
  port : 8888
  
spring:
    application:
      name : estore-central-config
    profiles:
      active: dev,test,prod
    cloud:
      config:
        server:
          git:
            uri: https://github.com/saravananjayagopal/estore-configrations
            search-paths : estore-central-config/
            
            

management:
  security:
     enabled: false
  